# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - ./bin/hugo version
  - ./bin/hugo
  - echo fokke.org > public/CNAME
  - echo '[![build status](https://travis-ci.org/foxey/foxey.github.io.svg?branch=hugo-src)](https://travis-ci.org/foxey/foxey.github.io)' > public/README.md
  - echo '# [fokke.org](http://fokke.org)' >> public/README.md
  - echo 'Static files for my website built with [Hugo](https://gohugo.io)' >> public/README.md
  

# Deploy to GitHub pages
deploy:
  provider: pages
  target_branch: master
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: hugo-src
